version: '2'

# Cluster nertwork configuration
networks:
 Hadoop:
   external: true

# Persistent volumes configuration
volumes:
 HadoopV0:
 HadoopV1:
 HadoopV2:
 HadoopN:

# Containers configuration
services:

#Namenode config
 hadoop-nn:
  image: uhopper/hadoop-namenode
  hostname: hadoop-nn
  container_name: hadoop-nn
  ports:
    - "8020:8020"
  networks: 
    Hadoop:
       ipv4_address: 172.19.0.2
  volumes:
    - HadoopN:/hadoop/dfs/name
  environment:
    - CLUSTER_NAME=cKHadoop
    - HDFS_CONF_dfs_replication=3
    - HDFS_CONF_dfs_client_use_datanode_hostname=true
    - HDFS_CONF_dfs_blocksize=64m

#Datanodes config
 hadoop-dn0:
  image: uhopper/hadoop-datanode
  hostname: hadoop-dn0
  container_name: hadoop-dn0
  networks: 
    Hadoop:
       ipv4_address: 172.19.0.10
  volumes:
    - HadoopV0:/hadoop/dfs/data
  environment:
    - CLUSTER_NAME=cKHadoop
    - HDFS_CONF_dfs_replication=3
    - CORE_CONF_fs_defaultFS=hdfs://hadoop-nn:8020
    - HDFS_CONF_dfs_blocksize=64m
 
 hadoop-dn1:
  image: uhopper/hadoop-datanode
  hostname: hadoop-dn1
  container_name: hadoop-dn1
  networks: 
    Hadoop:
       ipv4_address: 172.19.0.11
  volumes:
    - HadoopV1:/hadoop/dfs/data
  environment:
    - CLUSTER_NAME=cKHadoop
    - HDFS_CONF_dfs_replication=3
    - CORE_CONF_fs_defaultFS=hdfs://hadoop-nn:8020
    - HDFS_CONF_dfs_blocksize=64m

 hadoop-dn2:
  image: uhopper/hadoop-datanode
  hostname: hadoop-dn2
  container_name: hadoop-dn2
  networks: 
    Hadoop:
       ipv4_address: 172.19.0.12
  volumes:
    - HadoopV2:/hadoop/dfs/data
  environment:
    - CLUSTER_NAME=cKHadoop
    - HDFS_CONF_dfs_replication=3
    - CORE_CONF_fs_defaultFS=hdfs://hadoop-nn:8020
    - HDFS_CONF_dfs_blocksize=64m

#Resource manager config
 hadoop-rsm:
  image: uhopper/hadoop-resourcemanager
  hostname: hadoop-rsm
  container_name: hadoop-rsm
  networks: 
    Hadoop:
       ipv4_address: 172.19.0.19
  ports:
    - "8030:8030"
    - "8088:8088"
  environment:
    - CLUSTER_NAME=cKHadoop
    - HDFS_CONF_dfs_replication=3
    - CORE_CONF_fs_defaultFS=hdfs://hadoop-nn:8020
    - YARN_CONF_yarn_log___aggregation___enable=true
    - YARN_CONF_yarn_nodemanager_aux___services=mapreduce_shuffle
    - HDFS_CONF_dfs_blocksize=64m

#Node managers config
 hadoop-nm0:
  image: uhopper/hadoop-nodemanager
  hostname: hadoop-nm0
  container_name: hadoop-nm0
  networks: 
     Hadoop:
        ipv4_address: 172.19.0.20
  environment:
    - CLUSTER_NAME=cKHadoop
    - HDFS_CONF_dfs_replication=3
    - CORE_CONF_fs_defaultFS=hdfs://hadoop-nn:8020
    - YARN_CONF_yarn_resourcemanager_hostname=hadoop-rsm
    - YARN_CONF_yarn_log___aggregation___enable=true
    - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
    - YARN_CONF_yarn_nodemanager_aux___services=mapreduce_shuffle
    - HDFS_CONF_dfs_blocksize=64m

 hadoop-nm1:
  image: uhopper/hadoop-nodemanager
  hostname: hadoop-nm1
  container_name: hadoop-nm1
  networks: 
    Hadoop:
       ipv4_address: 172.19.0.21
  environment:
    - CLUSTER_NAME=cKHadoop
    - HDFS_CONF_dfs_replication=3
    - CORE_CONF_fs_defaultFS=hdfs://hadoop-nn:8020
    - YARN_CONF_yarn_resourcemanager_hostname=hadoop-rsm
    - YARN_CONF_yarn_log___aggregation___enable=true
    - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
    - YARN_CONF_yarn_nodemanager_aux___services=mapreduce_shuffle
    - HDFS_CONF_dfs_blocksize=64m

 hadoop-nm2:
  image: uhopper/hadoop-nodemanager
  hostname: hadoop-nm2
  container_name: hadoop-nm2
  networks: 
    Hadoop:
       ipv4_address: 172.19.0.22
  environment:
    - CLUSTER_NAME=cKHadoop
    - HDFS_CONF_dfs_replication=3
    - CORE_CONF_fs_defaultFS=hdfs://hadoop-nn:8020
    - YARN_CONF_yarn_resourcemanager_hostname=hadoop-rsm
    - YARN_CONF_yarn_log___aggregation___enable=true
    - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
    - YARN_CONF_yarn_nodemanager_aux___services=mapreduce_shuffle
    - HDFS_CONF_dfs_blocksize=64m
